### ISSUE TITLE
Lambdas defined inside match expressions cause crashes during code generation

### ISSUE THREAD

**Issue by lepoetemaudit** [alpaca-lang/alpaca#200]
Lambdas inside match expressions seem to trip something up in code generation. I believe it's another rewriting issue. An example of a failing module:

```fsharp
module bad

val fails : fn bool -> fn int -> int
let fails v =
    match v with
      | true -> fn y -> y * y
      | false -> fn y -> y + y
    
val succeeds : fn bool -> fn int -> int
let succeeds v =
    match v with
      | true -> (let f y = y * y in f)
      | false -> (let f y = y + y in f)
```

A stack trace of the resulting crash can be found here: https://gist.github.com/lepoetemaudit/43f41d8c8b753294b05694826ef738c3

The above example is contrived, but as far as I can tell a lambda declared anywhere on the right side of a match rule causes this issue.

**Comment by lepoetemaudit** [comment]
@j14159 I thought I might tackle this one myself, but if anything immediately springs to mind I'd be grateful for any pointers!

**Comment by j14159** [comment]
A quick scan suggests that `alpaca_codegen:rewrite_lambdas/1` isn't rewriting the contained lambdas as bindings properly (there's no actually expression generation defined for lambdas directly).  I think there are probably two options:

- define a version of `gen_expr/2` that can compile a fun directly.  I avoided this in the past due to some assumptions I made based on Erlang's [efficiency guide](http://erlang.org/doc/efficiency_guide/functions.html#id68971), choosing to bind lambdas to local variables with simple synthesized `let ... in` (this is what `rewrite_lambdas/1` does).
- properly handle clause bodies in the lambda rewriting logic as it doesn't look like we examine matches at all right now.

My _assumption_ is that the latter is more performant at runtime but do please note that's not based at all in experience or profiling, just assumptions from the guide above :)
