### ISSUE TITLE
Empty lines of whitespace more than `\n` not considered a break

### ISSUE THREAD

**Issue by j14159** [alpaca-lang/alpaca#69]
An empty line between function declarations is necessary to distinguish the two as separate functions but if that empty line contains any whitespace more than a `\n` it's not treated as an empty line/break between function definitions.

**Comment by lepoetemaudit** [comment]
I had a go at fixing this - figured it was low-hanging fruit - https://github.com/alpaca-lang/alpaca/commit/e5ddda3b2e131d5cd30b205defa28adc75f8e6de 

Unfortunately, I hit an odd bug in Leex which causes line numbers to be misreported in certain cases - https://bugs.erlang.org/browse/ERL-263, breaking quite a lot of other tests which explicitly match against line numbers. I tried compiling Erlang from the master branch which has the recent fix for this and it reported the line numbers correctly again.

I don't want to submit a PR that breaks line number reporting and would require making other tests more lax in what they match, but I wanted to leave this here so that the difficulty in resolving this is known. I don't know if it's possible to specify a patched version of parsetools when compiling Alpine, but otherwise fixing this is going to be pretty hard while supporting recent versions of OTP! Maybe there's a workaround, but I've not figured one out yet.

Maybe longer term, a hand rolled lexer would help us solve problems like this and would give other benefits, such as better error reporting, columns of syntax errors, etc. Elixir took this approach: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_tokenizer.erl while keeping Yecc for parsing.

**Comment by j14159** [comment]
Ouch, that's pretty unfortunate.  This is one of those situations where I wish we had the JVM's `String.trim()` I guess...

**Comment by lepoetemaudit** [comment]
Oops, of course, just sanitize the input. I used a regex on scan to remove space and tab chars between line breaks, seems effective and doesn't trash the line numbers.

**Comment by j14159** [comment]
Ha!  Didn't think of that, nice one.  Thanks for this!
